services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-todo-list-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"  
    depends_on:
      - mysql  

volumes:
  mysql_data:
