services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql                   
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  

volumes:
  mysql_data:
